[package]
authors = [
  "marsupialgutz <https://possums.xyz>",
  "nullobsi <https://nullob.si>",
]
description = "Simple color picker made in Rust"
edition = "2021"
name = "colorpick-rs"
version = "1.1.0"

[dependencies]
argparse = "0.2.2"
device_query = "1.0.0"
rdev = "0.5.1"
scrap = "0.5.0"
